const mongoose = require('mongoose');

const billSchema = new mongoose.Schema(
  {
    studentUsername: {
      type: String,
      required: [true, 'Student username is required'],
      ref: 'User',
    },
    month: {
      type: String, // Format: "March-2026"
      required: [true, 'Month is required'],
    },
    totalExpense: {
      type: Number,
      required: [true, 'Total expense is required'],
      min: 0,
    },
    totalStudents: {
      type: Number,
      required: [true, 'Total students count is required'],
      min: 1,
    },
    amountDue: {
      type: Number,
      required: [true, 'Amount due is required'],
      min: 0,
    },
    status: {
      type: String,
      enum: ['generated', 'paid', 'pending'],
      default: 'pending',
    },
    generatedBy: {
      type: String, // Username of the warden
      required: [true, 'Generated by is required'],
    },
    generatedOn: {
      type: Date,
      default: Date.now,
    },
    paidOn: {
      type: Date, // When the student paid
    },
    notes: {
      type: String,
    },
  },
  { timestamps: true }
);

billSchema.index({ studentUsername: 1, month: 1 }, { unique: true });
billSchema.index({ month: 1, status: 1 });
billSchema.index({ generatedOn: -1 });

module.exports = mongoose.model('Bill', billSchema);
